---
title: "Random Effect Models using lme4 of Recognition Memory Data"
author: "Mark Andrews"
date: "February 14, 2017"
output: pdf_document
---


```{r message=FALSE} 
library(lme4)
library(xtable)
library(pander)
```

```{r}
Df <- read.csv('../_cache/recognition.csv')

variables.to.convert <- c('expected', 'response', 'correct')
Df[variables.to.convert] <- lapply(Df[variables.to.convert],
                                   function(variable) {levels(variable) <- c(F, T); variable})
Df['X'] <- NULL

I <- !is.na(Df$posterior.predictions) & Df$cooccurrence.predictions > 0
Df.1 <- Df[I,]
```

```{r}
glmer.control <- glmerControl(optimizer="bobyqa",
                              optCtrl=list(maxfun=100000))

M.null <- glmer(response ~ expected  + (1|text) + (1|subject) + (1|word),
             data=Df.1,
             control = glmer.control,
             family=binomial)

Df.1$psi.pp <- log(Df.1$posterior.predictions)
Df.1$psi.cc <- log(Df.1$cooccurrence.predictions)
Df.1$psi.aa <- log(Df.1$association.predictions)

M.pp <- glmer(response ~ expected + psi.pp + 
                (psi.pp+expected|text) + 
                (psi.pp|subject) + 
                (1|word),
              data=Df.1,
              control = glmer.control,
              family=binomial)

M.cc <- glmer(response ~ expected + psi.cc + 
                (psi.cc+expected|text) + 
                (psi.cc|subject) + 
                (1|word),
              data=Df.1,
              control = glmer.control,
              family=binomial)

M.aa <- glmer(response ~ expected + psi.aa + 
                (psi.aa+expected|text) + 
                (psi.aa|subject) + 
                (1|word),
              data=Df.1,
              control = glmer.control,
              family=binomial)
```

```{r}
# Model fit results 
models = list(TopicModel=M.pp,
              CooccurrenceModel=M.cc,
              AssociationModel=M.aa,
              NullModel=M.null)

results <- rbind(sapply(models, BIC), 
                 sapply(models, AIC), 
                 sapply(models, function(arg) -2*logLik(arg)[1]))

rownames(results) <- c('BIC', 'AIC', 'Deviance')

pander(results)
```



